"""Additive, append-only P09 authority/evidence schema."""
import sqlite3
from pathlib import Path

class WorkLearningAuthorityMigrationError(RuntimeError): pass
TABLES=("hub_program_authority_classifications","hub_program_authority_relationships","hub_program_authority_claims","hub_program_authority_evidence","hub_program_authority_verifications","hub_program_authority_reviews","hub_program_authority_determinations")

def apply_work_learning_authority_schema(db_path: str|Path)->dict[str,object]:
 conn=sqlite3.connect(Path(db_path))
 try:
  conn.executescript("""
CREATE TABLE IF NOT EXISTS hub_program_authority_classifications(classification_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,source_reference_id TEXT NOT NULL,authority_tier TEXT NOT NULL CHECK(authority_tier IN('TIER_1_GOVERNING_AUTHORITY','TIER_2_HIGH_AUTHORITY_LEGAL_INTERPRETATION','TIER_3_PROFESSIONAL_EDUCATIONAL_SECONDARY_MATERIAL','TIER_4_CLAIMS_REQUIRING_INDEPENDENT_VERIFICATION')),classification_basis TEXT NOT NULL,classification_provenance TEXT NOT NULL,decision_origin TEXT NOT NULL CHECK(decision_origin IN('SYSTEM_SUGGESTED','OPERATOR_OR_FIDUCIARY','PROFESSIONAL')),professional_authority TEXT,actor TEXT NOT NULL,actor_capacity TEXT NOT NULL,prior_classification_id TEXT,created_at TEXT NOT NULL,FOREIGN KEY(prior_classification_id) REFERENCES hub_program_authority_classifications(classification_id));
CREATE INDEX IF NOT EXISTS idx_p09_classification_source ON hub_program_authority_classifications(program_id,source_reference_id,created_at);
CREATE TABLE IF NOT EXISTS hub_program_authority_claims(claim_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,issue_id TEXT NOT NULL CHECK(length(trim(issue_id))>0),proposition TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_program_authority_relationships(relationship_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,issue_id TEXT NOT NULL,claim_id TEXT,source_reference_id TEXT NOT NULL,classification_id TEXT NOT NULL,relationship_state TEXT NOT NULL CHECK(relationship_state IN('CONTROLLING','PERSUASIVE','SUPERSEDED','NOT_APPLICABLE','UNRESOLVED')),scope_modifier TEXT CHECK(scope_modifier IS NULL OR scope_modifier IN('FULL','PARTIAL','CONCURRENT')),relationship_basis TEXT NOT NULL,relationship_provenance TEXT NOT NULL,decision_origin TEXT NOT NULL CHECK(decision_origin IN('SYSTEM_SUGGESTED','OPERATOR_OR_FIDUCIARY','PROFESSIONAL')),human_confirmed INTEGER NOT NULL CHECK(human_confirmed IN(0,1)),professional_authority TEXT,express_evidence TEXT,objective_scope_evidence TEXT,prior_relationship_id TEXT,actor TEXT NOT NULL,actor_capacity TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(classification_id) REFERENCES hub_program_authority_classifications(classification_id),FOREIGN KEY(claim_id) REFERENCES hub_program_authority_claims(claim_id),FOREIGN KEY(prior_relationship_id) REFERENCES hub_program_authority_relationships(relationship_id));
CREATE TABLE IF NOT EXISTS hub_program_authority_evidence(evidence_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,claim_id TEXT NOT NULL,source_reference_id TEXT NOT NULL,relationship_type TEXT NOT NULL CHECK(relationship_type IN('DIRECT_SUPPORT','PARTIAL_SUPPORT','CONTRADICTS','QUALIFIES','CONTEXT_ONLY','DOES_NOT_SUPPORT','UNRESOLVED')),presentation_type TEXT NOT NULL CHECK(presentation_type IN('DIRECT_QUOTATION','PARAPHRASE','SUMMARY','REFERENCE_ONLY')),source_locator TEXT,evidence_basis TEXT NOT NULL,provenance TEXT NOT NULL,actor TEXT NOT NULL,actor_capacity TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(claim_id) REFERENCES hub_program_authority_claims(claim_id));
CREATE TABLE IF NOT EXISTS hub_program_authority_verifications(verification_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,claim_id TEXT,evidence_id TEXT,source_reference_id TEXT,classification_id TEXT,dimension TEXT NOT NULL CHECK(dimension IN('SOURCE_IDENTITY_VERIFIED','SOURCE_TEXT_VERIFIED','CITATION_VERIFIED','AUTHORITY_CLASSIFICATION_VERIFIED','CLAIM_SUPPORT_VERIFIED')),result_state TEXT NOT NULL CHECK(result_state IN('SOURCE_IDENTITY_VERIFIED','SOURCE_TEXT_VERIFIED','CITATION_VERIFIED','AUTHORITY_CLASSIFICATION_VERIFIED','CLAIM_SUPPORT_VERIFIED','SOURCE_IDENTITY_NOT_VERIFIED','SOURCE_TEXT_MISMATCH','CITATION_MISMATCH','AUTHORITY_CLASSIFICATION_DISPUTED','CLAIM_NOT_SUPPORTED','INSUFFICIENT_EVIDENCE')),verification_basis TEXT NOT NULL,provenance TEXT NOT NULL,decision_origin TEXT NOT NULL CHECK(decision_origin IN('SYSTEM_SUGGESTED','OPERATOR_OR_FIDUCIARY','PROFESSIONAL')),finalized INTEGER NOT NULL CHECK(finalized IN(0,1)),direct_source_comparison TEXT,objective_evidence TEXT,professional_authority TEXT,actor TEXT NOT NULL,actor_capacity TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_program_authority_reviews(review_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,claim_id TEXT NOT NULL,evidence_id TEXT,prior_review_id TEXT,authority_relationship_id TEXT,review_state TEXT NOT NULL CHECK(review_state IN('DETECTED','REVIEW_REQUIRED','UNDER_REVIEW','RESOLVED','UNRESOLVED','CLOSED_NO_CONFLICT')),review_lane TEXT NOT NULL CHECK(review_lane IN('SYSTEM_REVIEW','OPERATOR_OR_FIDUCIARY_REVIEW','PROFESSIONAL_REVIEW')),resolution_basis TEXT NOT NULL,provenance TEXT NOT NULL,supporting_source_reference_id TEXT NOT NULL,actor TEXT NOT NULL,actor_capacity TEXT NOT NULL,professional_authority TEXT,machine_generated INTEGER NOT NULL CHECK(machine_generated IN(0,1)),created_at TEXT NOT NULL,FOREIGN KEY(claim_id) REFERENCES hub_program_authority_claims(claim_id),FOREIGN KEY(prior_review_id) REFERENCES hub_program_authority_reviews(review_id),FOREIGN KEY(authority_relationship_id) REFERENCES hub_program_authority_relationships(relationship_id));
CREATE TABLE IF NOT EXISTS hub_program_authority_determinations(determination_id TEXT PRIMARY KEY,program_id TEXT NOT NULL,issue_id TEXT NOT NULL,claim_id TEXT NOT NULL,determination_state TEXT NOT NULL CHECK(determination_state IN('SUPPORTED','PARTIALLY_SUPPORTED','CONTRADICTED','MIXED','INSUFFICIENT_EVIDENCE','UNRESOLVED')),determination_basis TEXT NOT NULL,provenance TEXT NOT NULL,actor TEXT NOT NULL,actor_capacity TEXT NOT NULL,backtrace_json TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(claim_id) REFERENCES hub_program_authority_claims(claim_id));
CREATE INDEX IF NOT EXISTS idx_p09_claim_scope ON hub_program_authority_claims(program_id,issue_id,created_at);
CREATE INDEX IF NOT EXISTS idx_p09_relationship_scope ON hub_program_authority_relationships(program_id,issue_id,claim_id,source_reference_id,created_at);
CREATE INDEX IF NOT EXISTS idx_p09_evidence_claim ON hub_program_authority_evidence(program_id,claim_id,source_reference_id,created_at);
CREATE INDEX IF NOT EXISTS idx_p09_verification_scope ON hub_program_authority_verifications(program_id,claim_id,evidence_id,created_at);
CREATE INDEX IF NOT EXISTS idx_p09_review_claim ON hub_program_authority_reviews(program_id,claim_id,created_at);
CREATE INDEX IF NOT EXISTS idx_p09_determination_claim ON hub_program_authority_determinations(program_id,claim_id,created_at);
""")
  for table in TABLES:
   conn.executescript(f"CREATE TRIGGER IF NOT EXISTS p09_{table}_no_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT,'p09_append_only'); END; CREATE TRIGGER IF NOT EXISTS p09_{table}_no_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT,'p09_append_only'); END;")
  conn.commit(); rows={t:conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0] for t in TABLES}
  return {"schema_complete":True,"rows":rows,"records_created":0}
 except sqlite3.DatabaseError as exc:
  conn.rollback(); raise WorkLearningAuthorityMigrationError(str(exc)) from exc
 finally: conn.close()
